
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int LBRACE = 2;
  public static final int STRING = 10;
  public static final int EOF = 0;
  public static final int NUMERAL = 12;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 7;
  public static final int BLOCO = 13;
  public static final int EQUALS = 6;
  public static final int LPAREN = 8;
  public static final int LBRACKET = 4;
  public static final int RBRACE = 3;
  public static final int IDENTIFICADOR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "EQUALS",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "STRING",
  "IDENTIFICADOR",
  "NUMERAL",
  "BLOCO"
  };
}

